---
- name: Download files
  hosts: all

  tasks: 
  - name: Download file
    get_url:
       url: https://www.python.org/ftp/python/3.14.3/python-3.14.3-amd64.exe  
       dest: /tmp/script
       owner: ashishwayachal
       group: root
       mode: 0777
