#SPDX-License-Identifier: MIT-0
---
# tasks file for httpd_setup
- name: Install httpd
  yum:
    name: "{{ httpd_package_name }}"
    state: present
  become: true

- name: place custom HTML File
  copy: 
    src: index.html
    dest: /var/www/html/index.html
  become: true
- name: Start the service
  service:
    name: "{{ httpd_package_name }}"
    state: started
    enabled: yes
